# SPDX-License-Identifier: GPL-2.0

obj-m += snd-soc-cs35l43.o
snd-soc-cs35l43-y := cs35l43.o cs35l43-tables.o frankel-core-exports.o
ccflags-y += -I$(src)/include
ccflags-y += -include $(src)/frankel-fw-compat.h
